version: "3.4"

services:
    server:
        container_name: pivo-server
        build:
            context: ./
            args:
                - NODE_ENV=production
        ports: 
            - "8080:8080"
        networks:
            - network

networks:
    network:
        driver: bridge
