apiVersion: apps/v1
kind: Deployment
metadata:
  name: pivo-games-backend
spec:
  selector:
    matchLabels:
      app: pivo-games-backend
  replicas: 3
  template:
    metadata:
      labels:
        app: pivo-games-backend
    spec:
      containers:
        - name: api-server
          image: eu.gcr.io/PROJECT_ID/IMAGE:TAG
          ports:
            - containerPort: 8080