name: Linter

on: [push, pull_request]

jobs:
  linter:
    name: Lint code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
      - name: Install deps, eslint and plugins
        run: npm i
      - name: Run linter
        run: npm run lint